"""empty message

Revision ID: 3fca821426fc
Revises: 4a6f70cdb3ec
Create Date: 2020-10-11 20:26:35.879842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fca821426fc'
down_revision = '4a6f70cdb3ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auth_user', sa.Column('level', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auth_user', 'level')
    # ### end Alembic commands ###
