"""empty message

Revision ID: 4a6f70cdb3ec
Revises: 21123062df23
Create Date: 2020-10-11 17:36:45.696115

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a6f70cdb3ec'
down_revision = '21123062df23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auth_user',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=75), nullable=True),
    sa.Column('username', sa.String(length=75), nullable=True),
    sa.Column('password', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_auth_user_id'), 'auth_user', ['id'], unique=False)
    op.create_index(op.f('ix_auth_user_username'), 'auth_user', ['username'], unique=True)
    op.create_table('weapon',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=75), nullable=True),
    sa.Column('characteristic1', sa.Float(), nullable=True),
    sa.Column('characteristic2', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weapon_id'), 'weapon', ['id'], unique=False)
    op.create_index(op.f('ix_weapon_name'), 'weapon', ['name'], unique=True)
    op.create_table('user_weapons',
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('weapon_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['auth_user.id'], ),
    sa.ForeignKeyConstraint(['weapon_id'], ['weapon.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_weapons')
    op.drop_index(op.f('ix_weapon_name'), table_name='weapon')
    op.drop_index(op.f('ix_weapon_id'), table_name='weapon')
    op.drop_table('weapon')
    op.drop_index(op.f('ix_auth_user_username'), table_name='auth_user')
    op.drop_index(op.f('ix_auth_user_id'), table_name='auth_user')
    op.drop_table('auth_user')
    # ### end Alembic commands ###
